# Generated by Django 6.0.7 on 2026-08-13 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tickers', models.JSONField(default=list, null=True, unique=True)),
                ('sic', models.CharField(max_length=10, null=True)),
                ('cik', models.CharField(max_length=10, null=True)),
                ('hq_country_code', models.CharField(default=None, max_length=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('cik',), name='unique_company_cik')],
            },
        ),
        migrations.CreateModel(
            name='ExternalSegmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('original_name', models.CharField(max_length=255)),
                ('external_id', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('exiobase_segment_name', models.CharField(default=None, max_length=255, null=True)),
                ('mapping_type', models.CharField(default=None, max_length=255, null=True)),
                ('validated', models.BooleanField(default=False)),
                ('skipped', models.BooleanField(default=False)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='unique_source_external_id')],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('country_code', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('external_sector', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companies.externalsegmenttype')),
            ],
        ),
        migrations.CreateModel(
            name='SectorialRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.FloatField()),
                ('currency', models.CharField(max_length=5)),
                ('year', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectorial_revenues', to='companies.company')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectorial_revenues', to='companies.sector')),
            ],
        ),
        migrations.AddConstraint(
            model_name='sector',
            constraint=models.UniqueConstraint(fields=('company', 'year', 'country_code', 'external_sector'), name='unique_company_year_country_code_external_sector'),
        ),
        migrations.AddConstraint(
            model_name='sectorialrevenue',
            constraint=models.UniqueConstraint(fields=('company', 'sector'), name='unique_company_sector'),
        ),
    ]
